telegram:
  bot:
    userName: null
    token: null

clickUp:
  api:
    token: null
  url: null
  listId: null

project:
  id: "scumerbot"

google:
  client:
    id: null
    secret: null
  auth:
    uri: null
  token:
    uri: null
    path: null
  redirect:
    uris: null

sheets:
  range: null
  spreadsheetId: null

logging:
  level:
    root: INFO
    com:
      crypto: DEBUG

server:
  port: 8081

calendar:
  calendarId: null
